# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvstore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rkvstore.proto\x12\nlearn_raft\"&\n\nGetCommand\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_key\"j\n\x12GetCommandResponse\x12\x12\n\x05\x66ound\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x10\n\x03key\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_foundB\x06\n\x04_keyB\x08\n\x06_value\"l\n\nSetCommand\x12\x17\n\nrequest_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03key\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_request_idB\x06\n\x04_keyB\x08\n\x06_value\"t\n\x12SetCommandResponse\x12\x17\n\nrequest_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x16.learn_raft.StatusCodeH\x01\x88\x01\x01\x42\r\n\x0b_request_idB\t\n\x07_status*4\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\x12\n\x0eSTATUS_FAILURE\x10\x01\x32\x91\x01\n\rKeyValueStore\x12?\n\x03get\x12\x16.learn_raft.GetCommand\x1a\x1e.learn_raft.GetCommandResponse\"\x00\x12?\n\x03set\x12\x16.learn_raft.SetCommand\x1a\x1e.learn_raft.SetCommandResponse\"\x00\x62\x06proto3')

_STATUSCODE = DESCRIPTOR.enum_types_by_name['StatusCode']
StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
STATUS_SUCCESS = 0
STATUS_FAILURE = 1

_GETCOMMAND = DESCRIPTOR.message_types_by_name['GetCommand']
_GETCOMMANDRESPONSE = DESCRIPTOR.message_types_by_name['GetCommandResponse']
_SETCOMMAND = DESCRIPTOR.message_types_by_name['SetCommand']
_SETCOMMANDRESPONSE = DESCRIPTOR.message_types_by_name['SetCommandResponse']
GetCommand = _reflection.GeneratedProtocolMessageType('GetCommand', (_message.Message,), {
    'DESCRIPTOR': _GETCOMMAND,
    '__module__': 'kvstore_pb2'
    # @@protoc_insertion_point(class_scope:learn_raft.GetCommand)
})
_sym_db.RegisterMessage(GetCommand)

GetCommandResponse = _reflection.GeneratedProtocolMessageType('GetCommandResponse', (_message.Message,), {
    'DESCRIPTOR': _GETCOMMANDRESPONSE,
    '__module__': 'kvstore_pb2'
    # @@protoc_insertion_point(class_scope:learn_raft.GetCommandResponse)
})
_sym_db.RegisterMessage(GetCommandResponse)

SetCommand = _reflection.GeneratedProtocolMessageType('SetCommand', (_message.Message,), {
    'DESCRIPTOR': _SETCOMMAND,
    '__module__': 'kvstore_pb2'
    # @@protoc_insertion_point(class_scope:learn_raft.SetCommand)
})
_sym_db.RegisterMessage(SetCommand)

SetCommandResponse = _reflection.GeneratedProtocolMessageType('SetCommandResponse', (_message.Message,), {
    'DESCRIPTOR': _SETCOMMANDRESPONSE,
    '__module__': 'kvstore_pb2'
    # @@protoc_insertion_point(class_scope:learn_raft.SetCommandResponse)
})
_sym_db.RegisterMessage(SetCommandResponse)

_KEYVALUESTORE = DESCRIPTOR.services_by_name['KeyValueStore']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _STATUSCODE._serialized_start = 405
    _STATUSCODE._serialized_end = 457
    _GETCOMMAND._serialized_start = 29
    _GETCOMMAND._serialized_end = 67
    _GETCOMMANDRESPONSE._serialized_start = 69
    _GETCOMMANDRESPONSE._serialized_end = 175
    _SETCOMMAND._serialized_start = 177
    _SETCOMMAND._serialized_end = 285
    _SETCOMMANDRESPONSE._serialized_start = 287
    _SETCOMMANDRESPONSE._serialized_end = 403
    _KEYVALUESTORE._serialized_start = 460
    _KEYVALUESTORE._serialized_end = 605
# @@protoc_insertion_point(module_scope)
